version: '3.7'
services:
  ducatusx:
    # image: 'parity/parity:${PARITY_VERSION}'
    image: 'openethereum/openethereum:${PARITY_VERSION}'
    volumes:
      - '${PARITY_WORKER_PATH}/data:/srv/ducatusx/'
      - '${PARITY_WORKER_PATH}/keys:/srv/keys/'
      - "${PARITY_WORKER_PATH}/config.toml:/srv/config/config.toml"
      - "${PARITY_WORKER_PATH}/chain.json:/srv/config/chain.json"
      - "${PARITY_WORKER_PATH}/node.pwd:/srv/config/node.pwd"
      
    user: root
    restart: unless-stopped
    command:
      - --config=/srv/config/config.toml
    ports:
        # testnet
      - "8545:8545/tcp"
      - "8455:8455/tcp"
      - "30300:30300/tcp"
      - "30300:30300/udp"

        # mainnet
      - "8546:8546/tcp"
      - "8456:8456/tcp"
      - "30301:30301/tcp"
      - "30301:30301/udp"
  
