version: '3.7'
services:
  openethereum-1:
    image: 'parity/parity:${PARITY_VERSION}'
    # image: 'openethereum/openethereum:${OPENETHEREUM_VERSION}'
    volumes:
      - './data:/srv/ducatusx/'
      - './keys:/srv/keys/'
      - "./config.toml:/srv/config/config.toml"
      - "./chain.json:/srv/config/chain.json"
      - "./node.pwd:/srv/config/node.pwd"
      
    user: root
    restart: unless-stopped
    command:
      - --config=/srv/config/config.toml
    ports:
        # testnet
      - "8545:8545/tcp"
      - "8455:8455/tcp"
      - "30300:30300/tcp"
      - "30300:30300/udp"

        # mainnet
      - "8546:8546/tcp"
      - "8456:8456/tcp"
      - "30301:30301/tcp"
      - "30301:30301/udp"

