- name: Build and deploy nodes
  hosts: all
  become: yes
  vars_files:
  - "../../vars/nodes.yml"

  tasks:
  - name: Tear down existing services
    command:
      cmd: >
        docker-compose
        -f {{ manager_workdir }}/{{ docker_compose_file }}
        down


  - name: Delete project directory
    file:
      path: "{{ manager_workdir }}"
      state: absent
      
      
