- name: Start nodes
  hosts: all
  become: yes
  vars_files:
  - "../../vars/nodes.yml"

  tasks:
  - name: Start services
    command:
      cmd: >
        docker-compose
        -f {{ workdir }}/{{ docker_compose_file }}
        start