- name: Stop nodes
  hosts: all
  vars_files:
  - "../../vars/nodes.yml"

  tasks:
  - name: Stop services
    command:
      cmd: >
        docker-compose
        -f {{ manager_workdir }}/{{ docker_compose_file }}
        stop