- name: Setup common backend configurations
  hosts: all
  become: yes
  vars_files:
    - "../vars/nodes.yml"


  tasks:
    - name: Create directory
      file:
        path: "/var/www"
        state: directory

    - name: Setup manager 
      block:
        - name: Clone repository
          git:
            repo: https://github.com/DUCATUS-revival/ducatusx.git
            dest: "{{ manager_workdir }}"

        - name: Set env
          template: 
            src: ../templates/env.j2
            dest: "{{ manager_workdir }}/.env"

      # when: (is_swarm_manager is defined) and (is_swarm_manager == True)

    - name: Create config directory
      file:
        path: "{{ worker_config_path }}"
        state: directory

    - name: Create config-data directory
      file:
        path: "{{ worker_config_path }}/data"
        state: directory
    
    - name: Set configurations (testnet)
      block:
        - name: Copy chain.json (testnet)
          copy:
            src: ../../chain.testnet.json
            dest: "{{ worker_config_path }}/chain.json"
            remote_src: False

        - name: Set config (testnet)
          template: 
            src: ../templates/config.testnet.toml.j2
            dest: "{{ worker_config_path }}/config.toml"
            # owner: "{{ ansible_user }}"
            # group: "{{ ansible_user }}"
            mode: 0644
          
        - name: Copy keys (testnet)
          ansible.posix.synchronize:
            src: "../keys/testnet/{{ inventory_hostname }}/keys/"
            dest: "{{ worker_config_path }}/keys"
        
        - name: Copy node.pwd (testnet)
          ansible.posix.synchronize:
            src: "../keys/testnet/{{ inventory_hostname }}/node.pwd"
            dest: "{{ worker_config_path }}/node.pwd"

      when: is_testnet == True

    - name: Set configurations (mainnet)
      block:
        - name: Copy chain.json (mainnet)
          copy:
            src: ../../chain.mainnet.json
            dest: "{{ worker_config_path }}/chain.json"
            remote_src: False

        - name: Set config (mainnet)
          template: 
            src: ../templates/config.mainnet.toml.j2
            dest: "{{ worker_config_path }}/config.toml"
            # owner: "{{ ansible_user }}"
            # group: "{{ ansible_user }}"
            mode: 0644

        - name: Copy keys (mainnet)
          ansible.posix.synchronize:
            src: "../keys/mainnet/{{ inventory_hostname }}/keys/"
            dest: "{{ worker_config_path }}/keys"
        
        - name: Copy node.pwd (mainnet)
          ansible.posix.synchronize:
            src: "../keys/mainnet/{{ inventory_hostname }}/node.pwd"
            dest: "{{ worker_config_path }}/node.pwd"
      
      when: is_testnet == False
